# Generated by Django 4.1.7 on 2023-02-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Наименование')),
                ('answer', models.TextField(verbose_name='Наименование')),
                ('datetime', models.DateTimeField(verbose_name='Дата/время')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.category', verbose_name='Категория')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.field', verbose_name='Область')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
        ),
    ]
