# Generated by Django 4.1.7 on 2023-03-09 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0003_questionanswer_datetime_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="id_post",
            field=models.IntegerField(default=0, verbose_name="ИД поста"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата/время ответа"
            ),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.field",
                verbose_name="Область",
            ),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Специалист",
            ),
        ),
    ]
