# Generated by Django 4.1.7 on 2023-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_userforpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswerlog",
            name="answer_text",
            field=models.TextField(default="", verbose_name="Ответ"),
            preserve_default=False,
        ),
    ]
