# Generated by Django 4.1.7 on 2023-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_questionanswerlog_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswerlog",
            name="answer_text",
            field=models.TextField(null=True, verbose_name="Ответ"),
        ),
    ]
