# Generated by Django 4.1.7 on 2023-03-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_alter_questionanswerlog_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswerlog",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.questionanswer",
                verbose_name="Ответ в базе",
            ),
        ),
        migrations.AlterField(
            model_name="questionanswerlog",
            name="answer_text",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="questionanswerlog",
            name="datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата/время ответа"
            ),
        ),
    ]
