# Generated by Django 4.1.7 on 2023-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_questionanswerlog_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="it_test",
            field=models.BooleanField(blank=True, null=True, verbose_name="Это тест"),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="it_test",
            field=models.BooleanField(blank=True, null=True, verbose_name="Это тест"),
        ),
        migrations.AddField(
            model_name="questionanswerlog",
            name="it_test",
            field=models.BooleanField(blank=True, null=True, verbose_name="Это тест"),
        ),
        migrations.AddField(
            model_name="userforpost",
            name="it_test",
            field=models.BooleanField(blank=True, null=True, verbose_name="Это тест"),
        ),
    ]
