# Generated by Django 4.1.7 on 2023-03-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_category_it_test_questionanswer_it_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswerlog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="questionanswerlog",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
    ]
