# Generated by Django 4.1.7 on 2023-03-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_questionanswerlog_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstantData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("value", models.CharField(max_length=300, verbose_name="Значение")),
            ],
        ),
    ]
