# Generated by Django 4.1.7 on 2023-03-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_constantdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswerlog",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.questionanswer",
                verbose_name="Ответ в базе",
            ),
        ),
    ]
