# Generated by Django 4.1.7 on 2023-03-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_questionanswerlog_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="it_test",
            field=models.BooleanField(default=False, verbose_name="Это тест"),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="it_test",
            field=models.BooleanField(default=False, verbose_name="Это тест"),
        ),
        migrations.AlterField(
            model_name="questionanswerlog",
            name="it_test",
            field=models.BooleanField(default=False, verbose_name="Это тест"),
        ),
        migrations.AlterField(
            model_name="userforpost",
            name="it_test",
            field=models.BooleanField(default=False, verbose_name="Это тест"),
        ),
    ]
