# Generated by Django 4.1.7 on 2023-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_alter_category_it_test_alter_questionanswer_it_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="id_post_test",
            field=models.IntegerField(default=0, verbose_name="ИД поста"),
        ),
    ]
