# Generated by Django 4.1.7 on 2023-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_category_id_post_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='reply_to_message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID предыдущего сообщения в ТГ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id_post_test',
            field=models.IntegerField(default=0, verbose_name='ИД тестового поста'),
        ),
    ]
