# Generated by Django 4.1.7 on 2023-03-14 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0015_questionanswerlog_reply_to_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Специалист'),
        ),
    ]
