# Generated by Django 4.1.7 on 2023-03-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_questionanswerlog_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='retarget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retarget_category', to='crm.category', verbose_name='Новая категория'),
        ),
    ]
