# Generated by Django 4.1.7 on 2023-03-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_questionanswerlog_retarget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='it_agreed',
            field=models.BooleanField(default=False, verbose_name='Не согласовано'),
        ),
        migrations.AlterField(
            model_name='questionanswerlog',
            name='retarget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retarget_category', to='crm.category', verbose_name='Старая категория'),
        ),
    ]
