# Generated by Django 4.1.7 on 2023-03-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_questionanswerlog_it_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='questionanswerlog',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
    ]
