# Generated by Django 4.1.7 on 2023-03-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_questionanswerlog_dislike_questionanswerlog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='id_message_answer',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID сообщения ответа в ТГ'),
        ),
    ]
