# Generated by Django 4.1.7 on 2023-03-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_questionanswerlog_id_message_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='id_question_autor',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID автора вопроса в ТГ'),
        ),
    ]
