# Generated by Django 4.1.7 on 2023-03-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_questionanswerlog_id_question_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='it_finaly',
            field=models.BooleanField(default=False, verbose_name='Финальный ответ'),
        ),
    ]
