# Generated by Django 4.1.7 on 2023-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_questionanswerlog_it_finaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerlog',
            name='it_finaly',
            field=models.BooleanField(default=False, verbose_name='Финальный ответ'),
        ),
    ]
