# Generated by Django 4.1.7 on 2023-03-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0025_questionanswerlog_comment_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswerlog",
            name="comment_answer",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий пользователя на ответ"
            ),
        ),
        migrations.CreateModel(
            name="TagsForFind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Тег")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
        ),
    ]
