# Generated by Django 4.1.7 on 2023-03-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_questionanswerlog_comment_answer_tagsforfind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='questionanswerlog',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'База данных'},
        ),
        migrations.AlterModelOptions(
            name='tagsforfind',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='userforpost',
            options={'verbose_name': 'Ответственнй сотрудник темы', 'verbose_name_plural': 'Ответственные сотрудники тем'},
        ),
    ]
