# Generated by Django 4.1.7 on 2023-04-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0027_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="questionanswerlog", name="comment_answer",),
        migrations.AddField(
            model_name="questionanswerlog",
            name="comment_retarget_category",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий при смене категории"
            ),
        ),
    ]
