# Generated by Django 4.1.7 on 2023-04-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0029_questionanswerlog_it_last_message_in_dialog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionanswerlog", name="it_last_message_in_dialog",
        ),
    ]
