# Generated by Django 4.1.7 on 2023-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0030_remove_questionanswerlog_it_last_message_in_dialog"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswerlog",
            name="it_last_message_in_dialog",
            field=models.BooleanField(
                default=True, verbose_name="Это последнее сообщение в диалоге"
            ),
        ),
    ]
