# Generated by Django 4.1.7 on 2023-04-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_alter_сhatmemberscount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='first_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.questionanswerlog', verbose_name='Начальный вопрос'),
        ),
    ]
