# Generated by Django 4.1.7 on 2023-05-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_questionanswerlog_first_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerlog',
            name='it_interim',
            field=models.BooleanField(default=False, verbose_name='Промежуточный ответ'),
        ),
    ]
