# Generated by Django 4.1.7 on 2023-11-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0035_questionanswerlog_it_interim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подразделение')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
        ),
        migrations.CreateModel(
            name='RequestToAddModerators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия инициалы')),
                ('login_tg', models.CharField(max_length=200, verbose_name='Логин в ТГ')),
                ('datatime_request', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания завявки')),
                ('datatime_create_moder', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время создания модератора')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('it_rejection', models.BooleanField(verbose_name='Отказ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
                ('categories', models.ManyToManyField(to='crm.category', verbose_name='Категории')),
                ('department', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='crm.department', verbose_name='Подразделение')),
            ],
        ),
    ]
