# Generated by Django 4.1.7 on 2023-11-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_department_requesttoaddmoderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoaddmoderators',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='requesttoaddmoderators',
            name='it_rejection',
            field=models.BooleanField(default=False, verbose_name='Отказ'),
        ),
    ]
