# Generated by Django 4.1.7 on 2023-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_alter_requesttoaddmoderators_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300, verbose_name='Стоп фраза')),
                ('type_message', models.IntegerField(choices=[(0, 'Спам'), (1, 'Промежуточный')], verbose_name='Тип сообщения')),
            ],
        ),
    ]
