# Generated by Django 4.1.7 on 2023-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_stopphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopphrase',
            name='type_message',
            field=models.IntegerField(choices=[(0, 'Спам'), (1, 'Промежуточный')], error_messages={'blank': '3rfaf', 'invalid': 'zxc', 'invalid_choice': 'qqq', 'null': 'asdas'}, verbose_name='Тип сообщения'),
        ),
    ]
