# Generated by Django 4.1.7 on 2023-11-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_alter_stopphrase_type_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopphrase',
            name='type_message',
            field=models.IntegerField(choices=[(0, 'Спам'), (1, 'Промежуточный')], verbose_name='Тип сообщения'),
        ),
    ]
