# Generated by Django 4.1.7 on 2023-11-21 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0041_alter_stopphrase_type_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopphrase',
            options={'verbose_name': 'Стоп фраза', 'verbose_name_plural': 'Стоп фразы'},
        ),
        migrations.CreateModel(
            name='FeedbackFromUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Обратная связь')),
                ('datatime_feedback', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время сообщения')),
                ('like', models.IntegerField(default=0, verbose_name='Лайки')),
                ('dislike', models.IntegerField(default=0, verbose_name='Дизлайки')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(0, 'Зарегистрировано'), (1, 'Просмотрено'), (2, 'На рассмотрении'), (3, 'В работе'), (4, 'Завершено'), (5, 'Отклонено')], default=0, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
