# Generated by Django 4.1.7 on 2023-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_alter_stopphrase_options_feedbackfromusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackfromusers',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
