# Generated by Django 4.1.7 on 2023-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_alter_feedbackfromusers_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackfromusers',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
    ]
