# Generated by Django 4.1.7 on 2023-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_feedbackfromuserslikedislake'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackfromuserslikedislake',
            name='score',
            field=models.BooleanField(default=0, verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
