# Generated by Django 4.1.7 on 2023-11-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_feedbackfromuserslikedislake_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackfromuserslikedislake',
            name='type_feedback',
            field=models.IntegerField(choices=[(0, 'Предложение по улучшению'), (1, 'Сообщить об ошибке')], default=0, verbose_name='Тип обратной связи'),
        ),
    ]
