# Generated by Django 4.1.7 on 2023-11-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_feedbackfromuserslikedislake_type_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackfromuserslikedislake',
            name='type_feedback',
        ),
        migrations.AddField(
            model_name='feedbackfromusers',
            name='type_feedback',
            field=models.IntegerField(choices=[(0, 'Предложение по улучшению'), (1, 'Сообщить об ошибке')], default=0, verbose_name='Тип обратной связи'),
        ),
    ]
