# Generated by Django 4.1.7 on 2023-12-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0049_remove_feedbackfromuserslikedislake_type_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswerlog",
            name="encode",
            field=models.BooleanField(default=False, verbose_name="Вопрос кодирован"),
        ),
    ]
