# Generated by Django 4.1.7 on 2024-01-14 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0050_questionanswerlog_encode"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttoaddmoderators",
            name="type_action_request",
            field=models.IntegerField(
                choices=[(0, "Создать"), (1, "Изменить"), (2, "Удалить")],
                default=0,
                verbose_name="Тип дейтсвия заявки",
            ),
        ),
        migrations.AddField(
            model_name="requesttoaddmoderators",
            name="user_edit_delete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_edit_delete",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
