# Generated by Django 4.1.7 on 2024-01-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_requesttoaddmoderators_type_action_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesttoaddmoderators",
            name="department",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.department",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="requesttoaddmoderators",
            name="login_tg",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Логин в ТГ"
            ),
        ),
    ]
