# Generated by Django 4.1.7 on 2024-08-14 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0052_alter_requesttoaddmoderators_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoaddmoderators',
            name='user_edit_delete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_edit_delete', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
    ]
